package de.bht.mmi.iot.model.rest;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.ArrayList;

@DynamoDBTable(tableName = "Gateway")
public class Gateway {

    private String id;

    private String name;

    private ArrayList<String> clusterList;

    public Gateway() {
    }

    public Gateway(String name, ArrayList<String> clusterList) {
        this.name = name;
        this.clusterList = clusterList;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ArrayList<String> getClusterList() {
        return clusterList;
    }

    public void setClusterList(ArrayList<String> clusterList) {
        this.clusterList = clusterList;
    }
}
