package de.bht.mmi.iot.model.rest;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import de.bht.mmi.iot.converter.JodaDateTimeMarshaller;
import de.bht.mmi.iot.converter.SensorTypeMarshaller;
import org.joda.time.DateTime;

import java.util.List;

@DynamoDBTable(tableName = "Sensor")
public class Sensor {

    private String id;

    private String name;

    private SensorType sensorType;

    private String location;

    private List<String> attachedClusters;

    private String attachedGateway;

    private String owner;

    private DateTime creationDate;

    private boolean isActive;

    public Sensor(SensorType sensorType, String location, String attachedGateway,
                  List<String> attachedClusters, String owner, DateTime creationDate, boolean isActive) {
        this.sensorType = sensorType;
        this.location = location;
        this.attachedGateway = attachedGateway;
        this.attachedClusters = attachedClusters;
        this.owner = owner;
        this.creationDate = creationDate;
        this.isActive = isActive;
    }

    public Sensor() { }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    @DynamoDBMarshalling(marshallerClass = JodaDateTimeMarshaller.class)
    public DateTime getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(DateTime creationDate) {
        this.creationDate = creationDate;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public List<String> getAttachedClusters() {
        return attachedClusters;
    }

    public void setAttachedClusters(List<String> attachedClusters) {
        this.attachedClusters = attachedClusters;
    }

    public String getAttachedGateway() {
        return attachedGateway;
    }

    public void setAttachedGateway(String attachedGateway) {
        this.attachedGateway = attachedGateway;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    @DynamoDBMarshalling(marshallerClass = SensorTypeMarshaller.class)
    public SensorType getSensorType() {
        return sensorType;
    }

    public void setSensorType(SensorType sensorType) {
        this.sensorType = sensorType;
    }

}
