package de.bht.mmi.iot.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import de.bht.mmi.iot.converter.JodaDateTimeMarshaller;
import org.joda.time.DateTime;

import java.util.ArrayList;

@DynamoDBTable(tableName = "User")
public class User {

    private String userID;

    private String firstname;

    private String lastname;

    private String mail;

    private DateTime created;

    private String password;

    private int userRole;

    private ArrayList<String> sensorList;

    public User(String firstname, String lastname, String mail, String password) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.mail = mail;
        this.password = password;
    }

    public User(String firstname, String lastname, String mail, int userRole) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.mail = mail;
        this.userRole = userRole;
    }

    public User() {
    }

    @DynamoDBHashKey(attributeName = "userID")
    @DynamoDBAutoGeneratedKey
    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @DynamoDBMarshalling(marshallerClass = JodaDateTimeMarshaller.class)
    public DateTime getCreated() {
        return created;
    }

    public void setCreated(DateTime created) {
        this.created = created;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getUserRole() {
        return userRole;
    }

    public void setUserRole(int userRole) {
        this.userRole = userRole;
    }

    public ArrayList<String> getSensorList() {
        return sensorList;
    }

    public void setSensorList(ArrayList<String> sensorList) {
        this.sensorList = sensorList;
    }
}
