package de.bht.mmi.iot.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonSetter;
import de.bht.mmi.iot.constants.DbConstants;
import de.bht.mmi.iot.converter.JodaDateTimeMarshaller;
import org.joda.time.DateTime;

import javax.validation.constraints.NotNull;
import java.util.List;

@DynamoDBTable(tableName = DbConstants.TABLENAME_SENSOR)
public class Sensor {

    private String id;

    @NotNull
    private String name;

    private List<String> types;

    private String location;

    private String attachedCluster;

    private String attachedGateway;

    @NotNull
    private String owner;

    @NotNull
    private DateTime creationDate;

    private boolean isActive = false;

    public Sensor() { }

    @DynamoDBHashKey(attributeName = DbConstants.ATTRIBUTE_ID)
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isActive() {
        return isActive;
    }

    @JsonSetter("isActive")
    public void setActive(boolean active) {
        isActive = active;
    }

    @DynamoDBMarshalling(marshallerClass = JodaDateTimeMarshaller.class)
    public DateTime getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(DateTime creationDate) {
        this.creationDate = creationDate;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAttachedCluster() {
        return attachedCluster;
    }

    public void setAttachedCluster(String attachedCluster) {
        this.attachedCluster = attachedCluster;
    }

    public String getAttachedGateway() {
        return attachedGateway;
    }

    public void setAttachedGateway(String attachedGateway) {
        this.attachedGateway = attachedGateway;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public List<String> getTypes() {
        return types;
    }

    public void setTypes(List<String> types) {
        this.types = types;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Sensor)) return false;

        Sensor sensor = (Sensor) o;

        return !(id != null ? !id.equals(sensor.id) : sensor.id != null);

    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

}
